<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ComplaintController extends Controller
{
    /**
     * Get complaints belonging to the logged-in adopter.
     */
    public function index(Request $request)
    {
        $userId = $request->user()->id;

        /*
        |--------------------------------------------------------------------------
        | GET ALL COMPLAINTS USING RAW SQL
        |--------------------------------------------------------------------------
        */

        $complaints = DB::select(
            "
            SELECT
                complaints.id,
                complaints.subject,
                complaints.category,
                complaints.description,
                complaints.status,
                complaints.created_at,

                users.name AS user_name,
                users.email AS user_email

            FROM complaints

            INNER JOIN users
                ON complaints.user_id = users.id

            WHERE complaints.user_id = ?

            ORDER BY complaints.created_at DESC
            ",
            [$userId]
        );

        return response()->json([
            'complaints' => $complaints,
        ]);
    }


    /**
     * Create a new complaint.
     */
    public function store(Request $request)
    {
        /*
        |--------------------------------------------------------------------------
        | VALIDATION
        |--------------------------------------------------------------------------
        */

        $validated = $request->validate([
            'subject' => [
                'required',
                'string',
                'max:255',
            ],

            'category' => [
                'required',
                'string',
                'max:100',
            ],

            'description' => [
                'required',
                'string',
            ],
        ]);


        /*
        |--------------------------------------------------------------------------
        | INSERT COMPLAINT USING RAW SQL
        |--------------------------------------------------------------------------
        */

        DB::insert(
            "
            INSERT INTO complaints
            (
                user_id,
                subject,
                category,
                description,
                status,
                created_at,
                updated_at
            )
            VALUES
            (
                ?,
                ?,
                ?,
                ?,
                ?,
                NOW(),
                NOW()
            )
            ",
            [
                $request->user()->id,
                $validated['subject'],
                $validated['category'],
                $validated['description'],
                'Pending',
            ]
        );


        /*
        |--------------------------------------------------------------------------
        | GET THE LAST INSERTED COMPLAINT
        |--------------------------------------------------------------------------
        |
        | LAST_INSERT_ID() returns the ID generated by the previous INSERT.
        |
        */

        $result = DB::selectOne(
            "
            SELECT LAST_INSERT_ID() AS id
            "
        );

        $complaintId = $result->id;


        /*
        |--------------------------------------------------------------------------
        | GET THE CREATED COMPLAINT USING JOIN
        |--------------------------------------------------------------------------
        */

        $complaint = DB::selectOne(
            "
            SELECT
                complaints.id,
                complaints.subject,
                complaints.category,
                complaints.description,
                complaints.status,
                complaints.created_at,

                users.name AS user_name,
                users.email AS user_email

            FROM complaints

            INNER JOIN users
                ON complaints.user_id = users.id

            WHERE complaints.id = ?
            ",
            [$complaintId]
        );


        return response()->json([
            'message' => 'Complaint submitted successfully.',
            'complaint' => $complaint,
        ], 201);
    }


    /**
     * Show one complaint belonging to the logged-in adopter.
     */
    public function show(Request $request, $id)
    {
        $userId = $request->user()->id;


        /*
        |--------------------------------------------------------------------------
        | GET ONE COMPLAINT USING RAW SQL
        |--------------------------------------------------------------------------
        |
        | The user_id condition ensures that an adopter can only view
        | their own complaint.
        |
        */

        $complaint = DB::selectOne(
            "
            SELECT
                complaints.id,
                complaints.subject,
                complaints.category,
                complaints.description,
                complaints.status,
                complaints.created_at,

                users.name AS user_name,
                users.email AS user_email

            FROM complaints

            INNER JOIN users
                ON complaints.user_id = users.id

            WHERE complaints.id = ?
            AND complaints.user_id = ?
            ",
            [
                $id,
                $userId,
            ]
        );


        /*
        |--------------------------------------------------------------------------
        | COMPLAINT NOT FOUND
        |--------------------------------------------------------------------------
        */

        if (!$complaint) {
            return response()->json([
                'message' => 'Complaint not found.',
            ], 404);
        }


        /*
        |--------------------------------------------------------------------------
        | RESPONSE
        |--------------------------------------------------------------------------
        */

        return response()->json([
            'complaint' => $complaint,
        ]);
    }
}